# -*- coding: utf-8 -*-
"""Smart AI Chatbot for Policy Q&A using Vector Search.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MwGsMBubkF_WGzgEVVJ5TpZxhpgG3h6N
"""

pip install langchain faiss-cpu openai streamlit pandas

pip install -U langchain langchain-community faiss-cpu sentence-transformers

!pip install pypdf

!pip install langchain-huggingface

import os
os.environ["OPENAI_API_KEY"] = "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"

""". Load PDF **Document**


```
# This is formatted as code
```


"""

from google.colab import files
uploaded = files.upload()

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("policy.pdf")
docs = loader.load()


print("Number of pages:", len(docs))
print(docs[0].page_content[:500])

""" Split Text into **Chunks** ✅"""

from langchain_text_splitters import CharacterTextSplitter

splitter = CharacterTextSplitter(chunk_size=500,chunk_overlap=50)
chunks = splitter.split_documents(docs)

print("Total_chunks:", len(chunks))

"""📌 . Create Embeddings (FREE - HuggingFace)"""

from langchain_huggingface import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(model_name = "all-MiniLM-L6-v2")

"""📌  Store in Vector Database (FAISS)"""

from langchain_community.vectorstores import FAISS
db = FAISS.from_documents(chunks, embeddings)

print("Vector DB created sucessfully")

"""📌  Create Query Function (RAG Logic)"""

def ask_question(query):
  docs = db.similarity_search(query, k=3)

  context = " ".join([doc.page_content for doc in docs])

  answer = f"""
  Based on the policy document:

  {context}

  Question : {query}
  """

  return answer

"""📌  Test Chatbot"""

query = "What is refund policy?"
response = ask_question(query)

print(response)

"""📌 Interactive Chat (Optional)"""

while True:
  user_input = input("Ask a question (type 'exit' to stop): ")

  if user_input.lower() == "exit":
    break

  print(ask_question(user_input))

""":Project Explanation

This project is an AI-powered chatbot that can answer user queries based on a given document (such as a company policy PDF). I implemented a Retrieval-Augmented Generation (RAG) system, where the chatbot retrieves relevant information from the document and generates accurate responses.

First, I loaded and processed a PDF file containing policy data. Then, I split the document into smaller chunks to improve search efficiency. After that, I converted the text into vector embeddings using HuggingFace models and stored them in a FAISS vector database.

When a user asks a question, the system performs semantic search to find the most relevant chunks from the document. These chunks are then used to generate a contextual answer. This approach ensures that responses are accurate and based only on the provided data.

This project helped me understand key AI concepts like embeddings, vector databases, semantic search, and real-world chatbot development.
"""